version: "3.10"

services:
  web:
    build: .
    container_name: vcamp
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env

  worker:
    build: .
    command: celery -A vcamp.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - web

  flower:
    build: .
    command: celery -A vcamp.celery flower --address=0.0.0.0 --port=5555 --basic_auth=admin:admin
    ports:
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - worker
      - web